name: Setup

on:
  workflow_call:
    inputs:
      xdebug:
        required: false
        type: string
        default: "none"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: ${{ inputs.xdebug }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader